package com.trident.placement.entity;

import com.trident.placement.enums.ShortlistStatus;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Tracks shortlisting status for one student (application) for one elimination round.
 *
 * One row per (application, round) pair.
 * Round name is a VARCHAR — dynamic, derived from DriveJD selectionProcess.
 *
 * SQL (Oracle-compatible):
 * CREATE TABLE round_shortlist (
 *     id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     drive_id        NUMBER(19) NOT NULL,
 *     application_id  NUMBER(19) NOT NULL,
 *     round           VARCHAR2(255) NOT NULL,
 *     status          VARCHAR2(20)  NOT NULL DEFAULT 'PENDING',
 *     updated_by_id   NUMBER(19),
 *     comment         VARCHAR2(500),
 *     decided_at      TIMESTAMP,
 *     created_at      TIMESTAMP NOT NULL,
 *     updated_at      TIMESTAMP NOT NULL,
 *     CONSTRAINT uq_app_round UNIQUE (application_id, round),
 *     CONSTRAINT fk_rs_drive       FOREIGN KEY (drive_id)       REFERENCES DRIVES(ID)       ON DELETE CASCADE,
 *     CONSTRAINT fk_rs_application FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
 *     CONSTRAINT fk_rs_admin       FOREIGN KEY (updated_by_id)  REFERENCES admins(id)
 * );
 * CREATE INDEX idx_rs_drive_round  ON round_shortlist (drive_id, round);
 * CREATE INDEX idx_rs_status       ON round_shortlist (status);
 * CREATE INDEX idx_rs_drive_status ON round_shortlist (drive_id, status);
 * CREATE SEQUENCE SEQ_ROUND_SHORTLIST START WITH 1 INCREMENT BY 1;
 */
@Entity
@Table(
    name = "round_shortlist",
    uniqueConstraints = @UniqueConstraint(
        name = "uq_app_round",
        columnNames = {"application_id", "round"}
    ),
    indexes = {
        @Index(name = "idx_rs_drive_round",  columnList = "drive_id, round"),
        @Index(name = "idx_rs_status",        columnList = "status"),
        @Index(name = "idx_rs_drive_status",  columnList = "drive_id, status")
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RoundShortlist {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "round_shortlist_seq")
    @SequenceGenerator(
        name           = "round_shortlist_seq",
        sequenceName   = "SEQ_ROUND_SHORTLIST",
        allocationSize = 1
    )
    @Column(name = "id")
    private Long id;

    // ── Drive reference (denormalised for fast queries) ───────────────────────
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "drive_id", nullable = false,
                foreignKey = @ForeignKey(name = "fk_rs_drive"))
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private Drive drive;

    // ── Application reference ─────────────────────────────────────────────────
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "application_id", nullable = false,
                foreignKey = @ForeignKey(name = "fk_rs_application"))
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private Application application;

    // ── Dynamic round name — comes from DriveJD.selectionSteps ───────────────
    @Column(name = "round", nullable = false, length = 255)
    private String round;

    // ── Decision ──────────────────────────────────────────────────────────────
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    @Builder.Default
    private ShortlistStatus status = ShortlistStatus.PENDING;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "updated_by_id",
                foreignKey = @ForeignKey(name = "fk_rs_admin"))
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private Admin updatedBy;

    @Column(name = "remarks", length = 500)
    private String remarks;

    @Column(name = "decided_at")
    private LocalDateTime decidedAt;

    // ── Audit ─────────────────────────────────────────────────────────────────
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
