package com.trident.placement.entity;

import com.trident.placement.enums.NotificationType;
import com.trident.placement.enums.ShortlistStatus;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Audit log of every notification sent to a student about their round result.
 *
 * SQL (Oracle-compatible):
 * CREATE TABLE shortlist_notifications (
 *     id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *     application_id   NUMBER(19)   NOT NULL,
 *     round            VARCHAR2(255) NOT NULL,
 *     status_notified  VARCHAR2(20)  NOT NULL,
 *     notification_type VARCHAR2(20) NOT NULL DEFAULT 'BOTH',
 *     sent_at          TIMESTAMP,
 *     read_at          TIMESTAMP,
 *     created_at       TIMESTAMP NOT NULL,
 *     updated_at       TIMESTAMP NOT NULL,
 *     CONSTRAINT fk_sn_application FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE
 * );
 * CREATE INDEX idx_sn_app_round       ON shortlist_notifications (application_id, round);
 * CREATE INDEX idx_sn_status_notified ON shortlist_notifications (status_notified);
 * CREATE SEQUENCE SEQ_SHORTLIST_NOTIF START WITH 1 INCREMENT BY 1;
 */
@Entity
@Table(
    name = "shortlist_notifications",
    indexes = {
        @Index(name = "idx_sn_app_round",        columnList = "application_id, round"),
        @Index(name = "idx_sn_status_notified",   columnList = "status_notified")
    }
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ShortlistNotification {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "shortlist_notif_seq")
    @SequenceGenerator(
        name           = "shortlist_notif_seq",
        sequenceName   = "SEQ_SHORTLIST_NOTIF",
        allocationSize = 1
    )
    @Column(name = "id")
    private Long id;

    // ── Application ───────────────────────────────────────────────────────────
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "application_id", nullable = false,
                foreignKey = @ForeignKey(name = "fk_sn_application"))
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private Application application;

    // ── What was notified ─────────────────────────────────────────────────────
    @Column(name = "round", nullable = false, length = 255)
    private String round;

    @Enumerated(EnumType.STRING)
    @Column(name = "status_notified", nullable = false, length = 20)
    private ShortlistStatus statusNotified;

    @Enumerated(EnumType.STRING)
    @Column(name = "notification_type", nullable = false, length = 20)
    @Builder.Default
    private NotificationType notificationType = NotificationType.IN_APP;

    // ── Timestamps ────────────────────────────────────────────────────────────
    @Column(name = "sent_at")
    private LocalDateTime sentAt;

    @Column(name = "read_at")
    private LocalDateTime readAt;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
